# Generated by Django 2.2.5 on 2020-04-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bpub_data',
            new_name='bpub_date',
        ),
    ]
