# Generated by Django 2.2.5 on 2020-04-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20200415_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='booktest.BookInfo', verbose_name='图书'),
        ),
    ]
