# Generated by Django 2.2.5 on 2020-05-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
    ]
